# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'iett_lite' do
  pod 'rn-fetch-blob', :path => '../node_modules/rn-fetch-blob'

  pod 'RNGestureHandler', :path => '../node_modules/react-native-gesture-handler'

  pod 'React', :path => '../node_modules/react-native'
  pod 'yoga', :path => '../node_modules/react-native/ReactCommon/yoga'
end
